
@hostname = http://localhost
@port = 3001
@host = {{hostname}}:{{port}}

### 
# getAllBoards

GET {{host}}/api/boards
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyNCIsIl9pZCI6IjY0NjVkOGMwNDUwZWRlNDZiNTAyYjg4NSIsImlhdCI6MTY4NDM5ODQ0OH0.k70Qur91PjZ8FfuvoAX2g5ICi4SiKLObbUwdF3KN_6k


### 
# getAllBoards
# @query user

GET {{host}}/api/boards
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyNSIsIl9pZCI6IjY0NjVlMTQ3MDlmYzI0NjUxYmQzZWViOCIsImlhdCI6MTY4NDM5ODQxMX0.S5eVGmfVV1NSoCQFDu6r-iq5v_NttcpgAsktxg5JJXU


### 
# getBoardById
# @param :boardId

GET {{host}}/api/boards/6465dbd540442d3fbfc07b5b
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyNCIsIl9pZCI6IjY0NjVkOGMwNDUwZWRlNDZiNTAyYjg4NSIsImlhdCI6MTY4NDM5NjY5OX0.C6NfD8wIgiiFa3LjUMI5pxVQdNjZLSbe1a700oH2NsU

###
# createBoard
# @HTTP_HEADER x-auth-token: `jwt_token` (boardOwner)
# @body title

POST {{host}}/api/boards/
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyNSIsIl9pZCI6IjY0NjVlMTQ3MDlmYzI0NjUxYmQzZWViOCIsImlhdCI6MTY4NDM5ODQxMX0.S5eVGmfVV1NSoCQFDu6r-iq5v_NttcpgAsktxg5JJXU

{
  "name": "de maria pizarras"
}

###
# asignCollaboratorToBoard
# @HTTP_HEADER x-auth-token: `jwt_token` (boardOwner)
# @param :boardId
# @param :collaboratorId

PUT {{host}}/api/boards/645a09b955ce47738a4d984d/6459f896deeb61254ca46007
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFyaWEiLCJ1c2VybmFtZSI6InVzZXIyMiIsIl9pZCI6IjY0NWEwOWExNTVjZTQ3NzM4YTRkOTg0YSIsImlhdCI6MTY4MzYyMjQ2Mn0.KOxLYSHchr-w_-ocp9rU7TAzelvsN-2yHVvsNd4KiiY


###
# updateBoard
# @HTTP_HEADER x-auth-token: `jwt_token`
# @param :boardId
# @body title

PUT {{host}}/api/boards/6465dbd540442d3fbfc07b5b
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyNCIsIl9pZCI6IjY0NjVkOGMwNDUwZWRlNDZiNTAyYjg4NSIsImlhdCI6MTY4NDM5NzI4MH0.zWoQLhpnNO5p2E-YBD_cG6g1-FbtC2xVkzvH6lBYdbM

{
  "name": "updated Title"
}


### 
# deleteBoard
# @HTTP_HEADER x-auth-token: `jwt_token` (admin)
# @param :boardId

DELETE {{host}}/api/boards/6465dbd540442d3fbfc07b5b
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyNCIsIl9pZCI6IjY0NjVkOGMwNDUwZWRlNDZiNTAyYjg4NSIsImlhdCI6MTY4NDM5NzI4MH0.zWoQLhpnNO5p2E-YBD_cG6g1-FbtC2xVkzvH6lBYdbM


